tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "heroku/brew"

cask "iterm2"
cask "font-hack-nerd-font"
cask "hammerspoon"
cask "google-chrome"
cask "google-chrome-canary"
cask "maccy"
cask "dropbox"
cask "beyond-compare"
cask "postman"
cask "postico"
cask "ngrok"
cask "appcleaner"
cask "vlc"
cask "around"
cask "slack"
cask "trailer"
cask "notion"
# cask "sequel-pro"

brew "git"
brew "diff-so-fancy"
brew "nvim"
brew "tmux"
brew "ripgrep"
brew "fzf"
brew "rbenv"
brew "bat"
brew "tldr"
brew "htop"
brew "watch"
brew "parallel"
brew "ctags"
brew "yarn"
brew "node"
brew "nvm"
brew "awscli"
brew "ffmpeg"
brew "youtube-dl"

brew "heroku"
