name: eepi
root: ~/eepi

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Project hooks
# Runs on project start, always
# on_project_start: command
# Run on project start, the first time
# on_project_first_start: command
# Run on project start, after the first time
# on_project_restart: command
# Run on project exit ( detaching from tmux session )
# on_project_exit: command
# Run on project stop
# on_project_stop: command

on_project_first_start: open https://github.com/lord/slate; open https://lord.github.io/slate/

windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - # empty
  - server:
      layout: main-vertical
      panes:
        - be rails s
