alias be="bundle exec"
alias rr="bin/rails restart"
alias rc="bin/rails console -- --nomultiline"
alias rl="tail -f -n 1000 log/development.log"
alias rlc="tail -f -n 1000 log/development.log | rg -A 10 Controller"
